swagger: '2.0'
info:
  version: 1.0.0
  title: ubirch REST API
  description: >-
    This is the definition of the ubirch chain service REST API containing the
    following parts:|

    - chain service endpoints, to get information about certificates, blockchain
    entries and bitcoin/etherium anchors to notarize that a message was sent
basePath: /api/v1/chainService
produces:
  - application/json
paths:
  /:
    get:
      tags:
        - chain service
        - health
      summary: health monitor
      description: allows a quick check if the service is still up.
      responses:
        '200':
          description: everything is fine
          schema:
            $ref: '#/definitions/HealthResponse200'
        '400':
          description: something is not fine
          schema:
            $ref: '#/definitions/HealthResponse400'
  /deepCheck:
    get:
      tags:
        - chain service
        - health
      summary: deep check health monitor
      description: allows a deep check if the service is still up.
      responses:
        '200':
          description: everything is fine
          schema:
            $ref: '#/definitions/DeepCheckResponse200'
        '400':
          description: something is not fine
          schema:
            $ref: '#/definitions/DeepCheckResponse400'
        '500':
          description: server has a problem
          schema:
            $ref: '#/definitions/DeepCheckError500'
  /tx/deviceMsg:
    post:
      tags:
        - chain service
        - transaction
      summary: ''
      consumes:
        - application/json
      parameters:
        - in: body
          name: device message
          required: true
          schema:
            $ref: '#/definitions/DeviceMessageWriteRequest'
      responses:
        '200':
          description: >-
            Message was accepted and will be written to BigchainDB. There is no
            guarantee of this operation's success. Please use the explorer
            endpoints for this.
  /tx/deviceMsgHash:
    post:
      tags:
        - chain service
        - transaction
      summary: ''
      consumes:
        - application/json
      parameters:
        - in: body
          name: device message hash
          required: true
          schema:
            $ref: '#/definitions/DeviceMessageHashWriteRequest'
      responses:
        '200':
          description: >-
            Message was accepted and will be written to BigchainDB. There is no
            guarantee of this operation's success. Please use the explorer
            endpoints for this.
definitions:
  HealthResponse200:
    description: response if server is healthy
    type: object
    required:
      - version
      - status
      - message
    properties:
      version:
        type: string
      status:
        type: string
        enum:
          - OK
          - NOK
      message:
        type: string
    example:
      version: '1.0'
      status: OK
      message: Welcome to the ubirchChainService
  HealthResponse400:
    allOf:
      - $ref: '#/definitions/HealthResponse200'
    example:
      version: '1.0'
      status: NOK
      message: this is some error message
  DeepCheckResponse200:
    description: response if server is healthy
    type: object
    required:
      - status
      - message
    properties:
      status:
        type: boolean
      message:
        type: array
        items:
          type: string
    example:
      status: true
      messages:
        - Welcome to the ubirchChainService
  DeepCheckResponse400:
    allOf:
      - $ref: '#/definitions/DeepCheckResponse200'
    example:
      status: false
      messages:
        - this is some error message
        - and there's a second error
  DeviceMessageWriteRequest:
    description: transaction request to write a device message to BigchainDB
    type: object
    required:
      - id
      - payload
    properties:
      id:
        type: string
        description: >-
          a unique id that we remember ourselves. this is also used in the
          explorer methods to find out details about a transaction later.
      payload:
        $ref: '#/definitions/ValidJson'
    example:
      id: 29e2841b-6cf7-4cba-b0fb-39237521c334
      payload:
        t: 29.067
  DeviceMessageHashWriteRequest:
    description: transaction request to write a device message hash to BigchainDB
    type: object
    required:
      - id
      - hash
    properties:
      id:
        type: string
        description: >-
          a unique id that we remember ourselves. this is also used in the
          explorer methods to find out details about a transaction later.
      hash:
        type: string
        description: hash to remember
    example:
      id: 29e2841b-6cf7-4cba-b0fb-39237521c334
      hash: e9758380e3f9d2d0b9e0b13e424fcbf94a576c59dcf136b201832d1a687efc86
  ValidJson:
    description: any valid JSON
    type: object
    example:
      t: 29.067
  ErrorResponse:
    type: object
    description: error object with error code and message
    required:
      - version
      - status
      - errorType
      - errorMessage
    properties:
      version:
        type: string
      status:
        type: string
        enum:
          - NOK
      errorType:
        type: string
        enum:
          - ServerError
      errorMessage:
        type: string
        enum:
          - 'sorry, something went wrong on our end'
          - failed to run deep check
  DeepCheckError500:
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    example:
      version: '1.0'
      status: NOK
      errorType: ServerError
      errorMessage: 'sorry, something went wrong on our end'